code_syntax_highlight = "github-dark"

# ========= Border =========
file_panel_border = "#646A70"
sidebar_border = "#646A70"
footer_border = "#646A70"

# ========= Border Active =========
file_panel_border_active = "#D4D7DA"
sidebar_border_active = "#A06A6A"
footer_border_active = "#DDDBD7"
modal_border_active = "#646A70"

# ========= Background (bg) =========
full_screen_bg = "#14171A"
file_panel_bg = "#14171A"
sidebar_bg = "#14171A"
footer_bg = "#14171A"
modal_bg = "#14171A"

# ========= Foreground (fg) =========
full_screen_fg = "#D4D7DA"
file_panel_fg = "#D4D7DA"
sidebar_fg = "#90979C"
footer_fg = "#B8B2A8"
modal_fg = "#90979C"

# ========= Special Color =========
cursor = "#B8B2A8"
correct = "#7A9086"
error = "#A06A6A"
hint = "#90979C"
cancel = "#A06A6A"
# Gradient color can only have two color!
gradient_color = ["#5F7483", "#7C92A3"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#6E8494"
file_panel_top_path = "#B8B2A8"
file_panel_item_selected_fg = "#7C92A3"
file_panel_item_selected_bg = "#363b49"

# ========= Sidebar Special Items =========
sidebar_title = "#B8B2A8"
sidebar_item_selected_fg = "#E6E4E1"
sidebar_item_selected_bg = "#24292E"
sidebar_divider = "#A06A6A"

# ========= Modal Special Items =========
modal_cancel_fg = "#D66D6D"
modal_cancel_bg = "#4D3333"

modal_confirm_fg = "#6DD674"
modal_confirm_bg = "#384D33"

# ========= Help Menu =========
help_menu_hotkey = "#D4D7DA"
help_menu_title = "#A06A6A"
