#!/bin/sh

option1="󰒉󰏢Area select to clipboard"
option2="󰹑󰏢Full screen to clipboard"
option3=" 󰒉 Area select"
option4=" 󰹑 Full screen"
option5="󰒉󰕧Area select record"
option6="󰹑󰕧Full screen record"

selection=$(echo -e "$option4\n$option3\n$option2\n$option1\n$option6\n$option5" | rofi -dmenu -theme-str 'entry { enabled: false;} listview { lines: 6; scrollbar: false;} * { accent: @magenta2;}')


case "$selection" in
	"$option1") escrotum -sC -d 1;;
	"$option2") escrotum -C -d 1;;
	"$option3") escrotum -s -d 1 '~/Media/Images/screenshots/%Y-%m-%d-%H%M%S_$wx$h.png';;
	"$option4") escrotum -d 1 '~/Media/Images/screenshots/%Y-%m-%d-%H%M%S_$wx$h.png';;
	"$option5") escrotum -r '~/Media/Videos/recordings/%Y-%m-%d-%H%M%S_$wx$h.webm';;
	"$option6") escrotum -rs '~/Media/Videos/recordings/%Y-%m-%d-%H%M%S_$wx$h.webm';;
	*) exit 1;;
esac	

