wallpaper {
    monitor = eDP-1
    path = /home/david/Pictures/wallpapers/wallhaven-l852wr-colorized.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-2
    path = /home/david/Pictures/wallpapers/78572714_p0.jpg
    fit_mode = cover
    timeout = 45
}

wallpaper {
    monitor = HDMI-A2
    path = /home/david/Pictures/wallpapers/78572714_p0.jpg
    fit_mode = cover
}
