auth {
  fingerprint:enabled = true
}

background {
    monitor =
    path = screenshot
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 2
}

# shape {
#     monitor =
#     size = 360, 60
#     color = rgba(0, 0, 0, 0.0) # no fill
#     rounding = -1 # circle
#     border_size = 4
#     border_color = rgba(0, 207, 230, 1.0)
#
#     position = 0, 80
#     halign = center
#     valign = center
# }

input-field {
    monitor =
    size = 15%, 5%
    outline_thickness = 0
    inner_color = rgba(00000066) # no fill
    check_color = rgba(a292a333)
    fail_color = rgba(c4746e33)
    # outer_color = rgba(8ba4b0ee) rgba(8a9a7bee) 45deg
    # check_color=rgba(8a9a7bee) rgba(a292a3ee) 120deg
    # fail_color=rgba(a292a3ee) rgba(c4746eee) 40deg

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = -1

    position = 0, -60
    halign = center
    valign = center
}

label {
    monitor =
    text = Hi there, $USER
    color = rgba(200, 200, 200, 1.0)
    font_size = 22
    font_family = VictorMono Nerd Font
    shadow_passes = 1
    shadow_boost = 0.8

    position = 0, 10
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    
    color = rgba(200, 200, 200, 1.0)
    font_size = 64
    font_family = VictorMono Nerd Font
    shadow_passes = 1
    shadow_boost = 0.9

    position = 0, 180
    halign = center
    valign = center
}


