preload = /home/david/Pictures/wallpapers/wallhaven-jx2o3w_1920x1080.png
# preload = /home/david/Pictures/wallpapers/wallhaven-9djxk1.jpg
# preload = /home/david/Pictures/wallpapers/wallhaven-5g6m57.jpg
# preload = /home/david/Pictures/wallpapers/wallhaven-gpo1g3.jpg
wallpaper = , /home/david/Pictures/wallpapers/wallhaven-jx2o3w_1920x1080.png
