[font]
size = 12.0

[font.normal]
family = "VictorMono Nerd Font"

[window]
dynamic_padding = true
opacity = 0.8

[window.padding]
x = 8
y = 0

[cursor]
style = { shape = "Underline", blinking = "On" }
blink_interval = 500
blink_timeout = 0
unfocused_hollow = false

[env]
TERM="xterm-256color"

[general]
import = [
  "~/.config/alacritty/colorscheme.toml"
]
