# Colors (Tomorrow Night)

# Default colors
[colors.primary]
background = '#161719'
foreground = '#c5c8c6'

[colors.cursor]
text = '#161719'
cursor = '#c5c8c6'

# Normal colors
[colors.normal]
black   = '#161719'
red     = '#cc6666'
green   = '#b5bd68'
yellow  = '#f0c674'
blue    = '#81a2be'
magenta = '#b294bb'
cyan    = '#70c0ba'
white   = '#c5c8c6'

# Bright colors
[colors.bright]
black = '#282a2e'
red = '#e05252'
green = '#c6d350'
yellow = '#ffcc66'
blue = '#71a4d0'
magenta = '#bc84cd'
cyan = '#5cd6ce'
white = '#e5e6e5'
