[colors.primary]
background = '#141313'
foreground = '#cdc9c3'

[colors.normal]
black = '#0d0c0c'
blue = '#8ca8b6'
cyan = '#8ea4a2'
green = '#8a9a7b'
magenta = '#a292a3'
red = '#c4746e'
white = '#cdc9c3'
yellow = '#d0bc8d'

[[colors.indexed_colors]]
index = 16
color = '#ffa066'

[[colors.indexed_colors]]
index = 17
color = '#ff5d62'
