[colors]

[colors.primary]
background = "#0f0f0f"  # base00
foreground = "#d8d8d8"  # base05

[colors.normal]
black   = "#0f0f0f"  # base00
red     = "#b18f91"  # base08
green   = "#8aac8b"  # base0B
yellow  = "#b1ae8f"  # base0A
blue    = "#a5a0c2"  # base0D
magenta = "#ac8aac"  # base0E
cyan    = "#91b2b3"  # base0C
white   = "#d8d8d8"  # base05

[colors.bright]
black   = "#222222"  # base03
red     = "#b18f91"  # base08
green   = "#8aac8b"  # base0B
yellow  = "#b1ae8f"  # base0A
blue    = "#a5a0c2"  # base0D
magenta = "#ac8aac"  # base0E
cyan    = "#91b2b3"  # base0C
white   = "#f0f0f0"  # base07

