theme = "mytheme"

[editor]
cursorline = true
shell = ["zsh", "-c"]
scrolloff = 0
color-modes = true
popup-border = "all"
clipboard-provider = "wayland"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal.space]
r = [":write", ':run-shell-command python "%{buffer_name}"']
# "space"=r = ":sh python %%"
